# Generated by Django 5.2.4 on 2025-07-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='branch',
            field=models.CharField(max_length=50),
        ),
    ]
